version: "3.9"
services:
  app:
    build:
      context: ../.
    command: gunicorn -b 0.0.0.0:5000 run:app
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro